# main.yml

on: [push]

jobs:
  commit_job:
    runs-on: ubuntu-latest
    name: Env Test
    steps:
      # Checks out the repository for the action
      - name: Checkout
        uses: actions/checkout@v5
      # Runs the 'Env' Docker action
      - name: Docker env test
        id: env
        # References action in current repository
        uses: ./env-docker-action
        with:
          # Potential taint sources
          commit-message: ${{ github.event.head_commit.message }}
          commit-author: ${{ github.event.head_commit.author.name }}