on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Hello world action step
        id: hello
        uses: ./hello-world-docker-action
        with:
          who-to-greet: 'CSEC-759'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
  commit_job:
    runs-on: ubuntu-latest
    name: Commit info job
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Commit action step
        id: commit
        uses: ./commit-docker-action
        with:
          commit-message: ${{ github.event.head_commit.message }}
          commit-author: ${{ github.event.head_commit.author.name }}
      - name: Get the output time
        run: echo "The time was ${{ steps.commit.outputs.time }}"

