# main.yml

on: [push]

jobs:
  commit_job:
    runs-on: ubuntu-latest
    name: Commit Info
    steps:
      # Checks out the repository for the action
      - name: Checkout
        uses: actions/checkout@v5
      # Runs the 'Commit' Docker action
      - name: Commit action
        id: commit
        # References action in current repository
        uses: ./commit-docker-action
        with:
          # Potential taint sources
          commit-message: ${{ github.event.head_commit.message }}
          commit-author: ${{ github.event.head_commit.author.name }}
      # Gets the time from entrypoint.sh
      - name: Get output time
        run: echo "The time was ${{ steps.commit.outputs.time }}"